spring:
  application:
    name: ${APP_NAME:iot-service}
  config:
    import: optional:nacos:iot-service.yaml?server-addr=${NACOS_SERVER_ADDR:172.26.76.190:8848}&group=DEFAULT_GROUP, optional:nacos:common.yaml?server-addr=${NACOS_SERVER_ADDR:172.26.76.190:8848}&group=DEFAULT_GROUP&refreshEnabled=true
  cloud:
    nacos:
      config:
        server-addr: ${NACOS_SERVER_ADDR:172.26.76.190:8848}
        group: DEFAULT_GROUP
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:172.26.76.190:8848}
        namespace: ${NACOS_NAMESPACE:}

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: ${SERVER_PORT:8085}
