spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1
            - id: system-service
              uri: lb://system-service
              predicates:
                - Path=/system/**
              filters:
                - StripPrefix=1
            - id: resource-service
              uri: lb://resource-service
              predicates:
                - Path=/resource/**
              filters:
                - StripPrefix=1
            - id: sms-service
              uri: lb://sms-service
              predicates:
                - Path=/sms/**
              filters:
                - StripPrefix=1
            - id: iot-service
              uri: lb://iot-service
              predicates:
                - Path=/iot/**
              filters:
                - StripPrefix=1
            - id: emqx-auth
              uri: lb://emqx-auth
              predicates:
                - Path=/emqx/auth/**
            - id: iot-webhook
              uri: lb://iot-service
              predicates:
                - Path=/emqx/device-status
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders:
                  - "*"
                allowCredentials: false
                maxAge: 3600

knife4j:
  gateway:
    enabled: true
    strategy: discover
    discover:
      enabled: true
      version: openapi3
      excluded-services:
        - gateway
      oas3:
        url: /v3/api-docs?group=default

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
